# Simple Linear Regression

In [131]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [132]:
print(f'pandas  version: {pd.__version__}')
print(f'numpy   version: {np.__version__}')
print(f'seaborn version: {sns.__version__}')
print(pd.Timestamp.now())

pandas  version: 2.2.3
numpy   version: 2.0.1
seaborn version: 0.13.2
2025-07-09 12:02:20.607756

In [133]:
url='https://github.com/TheEconomist/big-mac-data/raw/master/output-data/big-mac-adjusted-index.csv'
df=pd.read_csv('../data/big-mac-adjusted-index.csv', parse_dates=['date'])
# df=pd.read_csv('../data/big-mac-adjusted-index.csv')
df.head()

,date,iso_a3,currency_code,name,local_price,dollar_ex,dollar_price,GDP_bigmac,adj_price,USD,EUR,GBP,JPY,CNY
0,2000-04-01,ARG,ARS,Argentina,2.50,1.000000,2.500000,8317.724800,1.941077,0.36397,NaN,-0.07809,0.09763,0.96247
1,2000-04-01,AUS,AUD,Australia,2.59,1.680000,1.541667,28023.744000,2.287635,-0.28631,NaN,-0.51761,-0.42567,0.02686
2,2000-04-01,BRA,BRL,Brazil,2.95,1.790000,1.648045,4511.789017,1.874144,-0.06873,NaN,-0.37055,-0.25058,0.33990
3,2000-04-01,GBR,GBP,Britain,1.90,0.632911,3.002000,20131.339789,2.148836,0.47950,NaN,0.00000,0.19060,1.12869
4,2000-04-01,CAN,CAD,Canada,2.85,1.470000,1.938776,24539.928589,2.226367,-0.07777,NaN,-0.37666,-0.25785,0.32689

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1645 entries, 0 to 1644
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1645 non-null   datetime64[ns]
 1   iso_a3         1645 non-null   object
 2   currency_code  1645 non-null   object
 3   name           1645 non-null   object
 4   local_price    1645 non-null   float64
 5   dollar_ex      1645 non-null   float64
 6   dollar_price   1645 non-null   float64
 7   GDP_bigmac     1645 non-null   float64
 8   adj_price      1645 non-null   float64
 9   USD            1645 non-null   float64
 10  EUR            1618 non-null   float64
 11  GBP            1645 non-null   float64
 12  JPY            1645 non-null   float64
 13  CNY            1645 non-null   float64
dtypes: datetime64[ns](1), float64(10), object(3)
memory usage: 180.1+ KB

In [135]:
df=df[(df['date'].dt.year==2019) & (df['date'].dt.month==1)]
df.head()

,date,iso_a3,currency_code,name,local_price,dollar_ex,dollar_price,GDP_bigmac,adj_price,USD,EUR,GBP,JPY,CNY
1021,2019-01-01,ARG,ARS,Argentina,75.00,37.455000,2.002403,15199.573616,3.252023,-0.40195,-0.47625,-0.36932,-0.25492,-0.35473
1022,2019-01-01,AUS,AUD,Australia,6.10,1.401640,4.352045,56235.238033,4.455652,-0.05132,-0.16917,0.00045,0.18192,0.02359
1023,2019-01-01,BRA,BRL,Brazil,16.90,3.717950,4.545516,8943.752112,3.068532,0.43877,0.26004,0.51728,0.79250,0.55238
1024,2019-01-01,GBR,GBP,Britain,3.19,0.783208,4.072992,46559.082339,4.171838,-0.05175,-0.16954,0.00000,0.18139,0.02313
1025,2019-01-01,CAN,CAD,Canada,6.77,1.331400,5.084873,40808.494010,4.003166,0.23372,0.08046,0.30104,0.53704,0.33113

## sklearn: LinearRegression

In [136]:
import sklearn
from sklearn.linear_model import LinearRegression
print(f'sklearn version: {sklearn.__version__}')

sklearn version: 1.7.0

In [137]:
model = LinearRegression() # create object/instance (create an instance from LinearRegression class)
model.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'positive': False,
 'tol': 1e-06}

In [138]:
df['GDP_bigmac'].head() # pandas Series

1021    15199.573616
1022    56235.238033
1023     8943.752112
1024    46559.082339
1025    40808.494010
Name: GDP_bigmac, dtype: float64

In [139]:
df[['GDP_bigmac']].head()

        GDP_bigmac
1021  15199.573616
1022  56235.238033
1023   8943.752112
1024  46559.082339
1025  40808.494010

In [140]:
X = df[['GDP_bigmac']]
y = df['dollar_price']
#y = df.dollar_price

In [141]:
model.fit(X, y) # step 2: fitting model

LinearRegression()

In [142]:
model.score(X, y) # step 3: model scoring

0.2517017715063411

In [143]:
# step 4: predicting
model.predict([
    [10000],
    [20000],
    [25000]
]) # numpy array: X 2-dim array

/home/cis/anaconda3/envs/ML/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([2.97761016, 3.25522244, 3.39402857])

In [144]:
model.intercept_

np.float64(2.6999978825873896)

In [145]:
model.coef_

array([2.77612277e-05])

$y=\alpha+\beta x$

In [146]:
model.intercept_ + model.coef_ * 9000

array([2.94984893])

In [147]:
model.predict([[9000]])

/home/cis/anaconda3/envs/ML/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([2.94984893])

In [148]:
# error
# model.predict(9000)

In [149]:
model.predict([[9000]]) # 2D array

/home/cis/anaconda3/envs/ML/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([2.94984893])

In [150]:
model.predict([[9000], 
               [40000]])

/home/cis/anaconda3/envs/ML/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([2.94984893, 3.81044699])

In [151]:
np.arange(5000, 50001, 2500)

array([ 5000,  7500, 10000, 12500, 15000, 17500, 20000, 22500, 25000,
       27500, 30000, 32500, 35000, 37500, 40000, 42500, 45000, 47500,
       50000])

In [152]:
np.arange(5000, 50000, 2500).reshape(-1, 1) # 2D

array([[ 5000],
       [ 7500],
       [10000],
       [12500],
       [15000],
       [17500],
       [20000],
       [22500],
       [25000],
       [27500],
       [30000],
       [32500],
       [35000],
       [37500],
       [40000],
       [42500],
       [45000],
       [47500]])

In [153]:
model.predict(np.arange(5000, 50001, 2500).reshape(-1, 1))

/home/cis/anaconda3/envs/ML/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([2.83880402, 2.90820709, 2.97761016, 3.04701323, 3.1164163 ,
       3.18581937, 3.25522244, 3.32462551, 3.39402857, 3.46343164,
       3.53283471, 3.60223778, 3.67164085, 3.74104392, 3.81044699,
       3.87985006, 3.94925313, 4.0186562 , 4.08805927])

In [154]:
np.linspace(5000, 50000, 20)

array([ 5000.        ,  7368.42105263,  9736.84210526, 12105.26315789,
       14473.68421053, 16842.10526316, 19210.52631579, 21578.94736842,
       23947.36842105, 26315.78947368, 28684.21052632, 31052.63157895,
       33421.05263158, 35789.47368421, 38157.89473684, 40526.31578947,
       42894.73684211, 45263.15789474, 47631.57894737, 50000.        ])

In [155]:
np.linspace(5000, 50000, 20).reshape(-1, 1)

array([[ 5000.        ],
       [ 7368.42105263],
       [ 9736.84210526],
       [12105.26315789],
       [14473.68421053],
       [16842.10526316],
       [19210.52631579],
       [21578.94736842],
       [23947.36842105],
       [26315.78947368],
       [28684.21052632],
       [31052.63157895],
       [33421.05263158],
       [35789.47368421],
       [38157.89473684],
       [40526.31578947],
       [42894.73684211],
       [45263.15789474],
       [47631.57894737],
       [50000.        ]])

In [156]:
model.predict(np.linspace(5000, 50000, 20).reshape(-1, 1))

/home/cis/anaconda3/envs/ML/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([2.83880402, 2.9045543 , 2.97030457, 3.03605485, 3.10180513,
       3.1675554 , 3.23330568, 3.29905595, 3.36480623, 3.43055651,
       3.49630678, 3.56205706, 3.62780733, 3.69355761, 3.75930789,
       3.82505816, 3.89080844, 3.95655871, 4.02230899, 4.08805927])

In [157]:
s=pd.Series(np.linspace(5000, 50000, 20))
s

0      5000.000000
1      7368.421053
2      9736.842105
3     12105.263158
4     14473.684211
5     16842.105263
6     19210.526316
7     21578.947368
8     23947.368421
9     26315.789474
10    28684.210526
11    31052.631579
12    33421.052632
13    35789.473684
14    38157.894737
15    40526.315789
16    42894.736842
17    45263.157895
18    47631.578947
19    50000.000000
dtype: float64

In [158]:
model.predict(s.to_frame())

/home/cis/anaconda3/envs/ML/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([2.83880402, 2.9045543 , 2.97030457, 3.03605485, 3.10180513,
       3.1675554 , 3.23330568, 3.29905595, 3.36480623, 3.43055651,
       3.49630678, 3.56205706, 3.62780733, 3.69355761, 3.75930789,
       3.82505816, 3.89080844, 3.95655871, 4.02230899, 4.08805927])

In [159]:
dx=pd.DataFrame(np.linspace(5000, 50000, 20), columns=['GDP_bigmac'])
dx

      GDP_bigmac
0    5000.000000
1    7368.421053
2    9736.842105
3   12105.263158
4   14473.684211
5   16842.105263
6   19210.526316
7   21578.947368
8   23947.368421
9   26315.789474
10  28684.210526
11  31052.631579
12  33421.052632
13  35789.473684
14  38157.894737
15  40526.315789
16  42894.736842
17  45263.157895
18  47631.578947
19  50000.000000

In [160]:
model.predict(dx)

array([2.83880402, 2.9045543 , 2.97030457, 3.03605485, 3.10180513,
       3.1675554 , 3.23330568, 3.29905595, 3.36480623, 3.43055651,
       3.49630678, 3.56205706, 3.62780733, 3.69355761, 3.75930789,
       3.82505816, 3.89080844, 3.95655871, 4.02230899, 4.08805927])

## Statsmodels: Simple Linear regression

In [161]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [162]:
# formula: response ~ predictor1 + predictor2
model_a = smf.ols(formula='dollar_price ~ GDP_bigmac', data=df).fit()

In [163]:
model_a.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:           dollar_price   R-squared:                       0.252
Model:                            OLS   Adj. R-squared:                  0.230
Method:                 Least Squares   F-statistic:                     11.77
Date:                Wed, 09 Jul 2025   Prob (F-statistic):            0.00156
Time:                        12:02:21   Log-Likelihood:                -53.601
No. Observations:                  37   AIC:                             111.2
Df Residuals:                      35   BIC:                             114.4
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.7000      0.306      8.813      0.000       2.078       3.322
GDP_bigmac  2.776e-05   8.09e-06      3.431      0.002    1.13e-05    4.42e-05
==============================================================================
Omnibus:                        0.343   Durbin-Watson:                   1.902
Prob(Omnibus):                  0.842   Jarque-Bera (JB):                0.023
Skew:                          -0.052   Prob(JB):                        0.988
Kurtosis:                       3.065   Cond. No.                     6.66e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.66e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [164]:
print(model_a.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           dollar_price   R-squared:                       0.252
Model:                            OLS   Adj. R-squared:                  0.230
Method:                 Least Squares   F-statistic:                     11.77
Date:                Wed, 09 Jul 2025   Prob (F-statistic):            0.00156
Time:                        12:02:21   Log-Likelihood:                -53.601
No. Observations:                  37   AIC:                             111.2
Df Residuals:                      35   BIC:                             114.4
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.7000      0.306      8.813      0.000       2.078       3.322
GDP_bigmac  2.776e-05   8.09e-06      3.431      0.002    1.13e-05    4.42e-05
==============================================================================
Omnibus:                        0.343   Durbin-Watson:                   1.902
Prob(Omnibus):                  0.842   Jarque-Bera (JB):                0.023
Skew:                          -0.052   Prob(JB):                        0.988
Kurtosis:                       3.065   Cond. No.                     6.66e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.66e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [165]:
model_a.pvalues

Intercept     2.072772e-10
GDP_bigmac    1.558660e-03
dtype: float64

In [166]:
model.intercept_ # sklearn

np.float64(2.6999978825873896)

In [167]:
model.coef_

array([2.77612277e-05])

In [168]:
print(f'{model.coef_[0]:.7f}')

0.0000278

## train-test-split

In [169]:
from sklearn.model_selection import train_test_split

In [170]:
len(df)

37

## method 1: split into (train, test)

In [171]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [172]:
model.fit(X_train, y_train) # step 2: fitting model

LinearRegression()

In [173]:
model.score(X_test, y_test) # step 3: model scoring

0.2566111442851442

In [174]:
# step 4: predicting
model.predict([
    [10000],
    [20000],
    [25000]
]) # numpy array: X 2-dim array

/home/cis/anaconda3/envs/ML/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([3.05122576, 3.33835867, 3.48192513])

In [175]:
model.intercept_

np.float64(2.7640928525782202)

In [176]:
model.coef_

array([2.87132911e-05])

$y=\alpha+\beta x$

In [177]:
model.intercept_ + model.coef_ * 9000

array([3.02251247])

In [178]:
model.predict([[9000]]) # 2D array

/home/cis/anaconda3/envs/ML/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([3.02251247])

In [179]:
model.predict([[9000], 
               [40000]])

/home/cis/anaconda3/envs/ML/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([3.02251247, 3.9126245 ])

In [180]:
np.arange(5000, 50001, 2500)

array([ 5000,  7500, 10000, 12500, 15000, 17500, 20000, 22500, 25000,
       27500, 30000, 32500, 35000, 37500, 40000, 42500, 45000, 47500,
       50000])

In [181]:
np.arange(5000, 50001, 2500).reshape(-1, 1) # 2D

array([[ 5000],
       [ 7500],
       [10000],
       [12500],
       [15000],
       [17500],
       [20000],
       [22500],
       [25000],
       [27500],
       [30000],
       [32500],
       [35000],
       [37500],
       [40000],
       [42500],
       [45000],
       [47500],
       [50000]])

In [182]:
model.predict(np.arange(5000, 50001, 2500).reshape(-1, 1))

/home/cis/anaconda3/envs/ML/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([2.90765931, 2.97944254, 3.05122576, 3.12300899, 3.19479222,
       3.26657545, 3.33835867, 3.4101419 , 3.48192513, 3.55370836,
       3.62549159, 3.69727481, 3.76905804, 3.84084127, 3.9126245 ,
       3.98440772, 4.05619095, 4.12797418, 4.19975741])

In [183]:
np.linspace(5000, 50000, 20)

array([ 5000.        ,  7368.42105263,  9736.84210526, 12105.26315789,
       14473.68421053, 16842.10526316, 19210.52631579, 21578.94736842,
       23947.36842105, 26315.78947368, 28684.21052632, 31052.63157895,
       33421.05263158, 35789.47368421, 38157.89473684, 40526.31578947,
       42894.73684211, 45263.15789474, 47631.57894737, 50000.        ])

In [184]:
np.linspace(5000, 50000, 20).reshape(-1, 1)

array([[ 5000.        ],
       [ 7368.42105263],
       [ 9736.84210526],
       [12105.26315789],
       [14473.68421053],
       [16842.10526316],
       [19210.52631579],
       [21578.94736842],
       [23947.36842105],
       [26315.78947368],
       [28684.21052632],
       [31052.63157895],
       [33421.05263158],
       [35789.47368421],
       [38157.89473684],
       [40526.31578947],
       [42894.73684211],
       [45263.15789474],
       [47631.57894737],
       [50000.        ]])

In [185]:
model.predict(np.linspace(5000, 50000, 20).reshape(-1, 1))

/home/cis/anaconda3/envs/ML/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([2.90765931, 2.97566447, 3.04366963, 3.1116748 , 3.17967996,
       3.24768512, 3.31569029, 3.38369545, 3.45170061, 3.51970578,
       3.58771094, 3.6557161 , 3.72372127, 3.79172643, 3.85973159,
       3.92773676, 3.99574192, 4.06374708, 4.13175224, 4.19975741])

In [186]:
s=pd.Series(np.linspace(5000, 50000, 20))
s

0      5000.000000
1      7368.421053
2      9736.842105
3     12105.263158
4     14473.684211
5     16842.105263
6     19210.526316
7     21578.947368
8     23947.368421
9     26315.789474
10    28684.210526
11    31052.631579
12    33421.052632
13    35789.473684
14    38157.894737
15    40526.315789
16    42894.736842
17    45263.157895
18    47631.578947
19    50000.000000
dtype: float64

In [187]:
model.predict(s.to_frame())

/home/cis/anaconda3/envs/ML/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([2.90765931, 2.97566447, 3.04366963, 3.1116748 , 3.17967996,
       3.24768512, 3.31569029, 3.38369545, 3.45170061, 3.51970578,
       3.58771094, 3.6557161 , 3.72372127, 3.79172643, 3.85973159,
       3.92773676, 3.99574192, 4.06374708, 4.13175224, 4.19975741])

In [188]:
dx=pd.DataFrame(np.linspace(5000, 50000, 20), columns=['GDP_bigmac'])
dx

      GDP_bigmac
0    5000.000000
1    7368.421053
2    9736.842105
3   12105.263158
4   14473.684211
5   16842.105263
6   19210.526316
7   21578.947368
8   23947.368421
9   26315.789474
10  28684.210526
11  31052.631579
12  33421.052632
13  35789.473684
14  38157.894737
15  40526.315789
16  42894.736842
17  45263.157895
18  47631.578947
19  50000.000000

In [189]:
model.predict(dx)

array([2.90765931, 2.97566447, 3.04366963, 3.1116748 , 3.17967996,
       3.24768512, 3.31569029, 3.38369545, 3.45170061, 3.51970578,
       3.58771094, 3.6557161 , 3.72372127, 3.79172643, 3.85973159,
       3.92773676, 3.99574192, 4.06374708, 4.13175224, 4.19975741])